### PR TITLE
Fix usage of cobalt after Angel mods pushed it to "crystal" tier.

### PR DESCRIPTION
**Pull request by domis86**
Fix usage of cobalt after Angel mods pushed it to "crystal" tier.

- replace it with aluminium, zinc, or steel bearing in recipes that are at "chunk" tier

Is needed because otherwise at some point is impossible to progress (at "intermediate structure components" and "leaching plant") - more info: https://mods.factorio.com/mod/MomosTweak/discussion/6114f8c44232fcfb072e08b7

### CODE REVIEW

**Comment by domis86** [comment]
@Archemide bump :)

**Comment by Archemide** [comment]
Sorry, I've been crazy busy with RL stuff lately. I've added you to both the mod portal and repo if you're interested.

**Comment by domis86** [comment]
> Sorry, I've been crazy busy with RL stuff lately. I've added you to both the mod portal and repo if you're interested.

Ok, thanks :+1:  I will try to push new version in next days.

**Comment by domis86** [comment]
Ok version updated (1.1.4)

**Pull request merged**
